-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema guitartrackr
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `guitartrackr` ;

-- -----------------------------------------------------
-- Schema guitartrackr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guitartrackr` ;
USE `guitartrackr` ;

-- -----------------------------------------------------
-- Table `guitartrackr`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitartrackr`.`users` ;

CREATE TABLE IF NOT EXISTS `guitartrackr`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` ENUM('user', 'admin') NULL DEFAULT 'user',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guitartrackr`.`songs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitartrackr`.`songs` ;

CREATE TABLE IF NOT EXISTS `guitartrackr`.`songs` (
  `song_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `artist` VARCHAR(100) NOT NULL,
  `difficulty` ENUM('easy', 'medium', 'hard') NULL,
  `tuning` VARCHAR(50) NULL,
  `tablature_url` VARCHAR(255) NULL,
  PRIMARY KEY (`song_id`),
  UNIQUE INDEX `id_UNIQUE` (`song_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guitartrackr`.`user_songs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitartrackr`.`user_songs` ;

CREATE TABLE IF NOT EXISTS `guitartrackr`.`user_songs` (
  `user_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `song_id`),
  INDEX `fk_users_has_songs_songs1_idx` (`song_id` ASC) VISIBLE,
  INDEX `fk_users_has_songs_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_songs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `guitartrackr`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_songs_songs1`
    FOREIGN KEY (`song_id`)
    REFERENCES `guitartrackr`.`songs` (`song_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
